name: Cleanup PR Image

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    permissions:
      contents: read
      packages: write
    uses: ljmerza/misc-actions/.github/workflows/cleanup-pr-image.yml@v2
    with:
      package-name: unifi_firmware
    secrets: inherit
